version: '3.8'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8896:80"
    container_name: app_nginx_ub
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: _docker/app/DockerFile
    volumes:
      - ./:/var/www/
    container_name: app_ub
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: users_balance
      POSTGRES_PASSWORD: users_balance
      POSTGRES_DB: users_balance
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5430:5432"
    container_name: postgres_db_ub